on:
    pull_request_target:
        types: [opened, synchronize]

jobs:
    pr-status-checks:
        name: PR Status Checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '22.12.0'
                  cache: 'npm'

            - name: Try to restore node_modules folder from cache
              id: cache-node-modules
              uses: actions/cache@v4
              with:
                  path: ./node_modules
                  key: npm-${{ hashFiles('./package-lock.json') }}

            - name: Otherwise install npm dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm ci

            - uses: ramp4-pcar4/status-checks@main
              id: pr-checks
              with:
                  gh-token: ${{ secrets.GITHUB_TOKEN }}
                  ts-command: 'npm run ts:check'
                  lint-command: 'npm run lint:check'
                  format-command: 'npm run format:check'

            - name: Typescript badge
              if: always()
              uses: RubbaBoy/BYOB@v1.3.0
              with:
                  name: 'tsbadge-${{ github.event.pull_request.head.repo.owner.login }}-${{ github.head_ref }}'
                  icon: typescript
                  label: 'Errors (PR)'
                  status: ${{ steps.pr-checks.outputs.ts-errors }}
                  color: blue
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Lint badge
              if: always()
              uses: RubbaBoy/BYOB@v1.3.0
              with:
                  name: 'lintbadge-${{ github.event.pull_request.head.repo.owner.login }}-${{ github.head_ref }}'
                  icon: codecov
                  label: 'Status (PR)'
                  status: 'Errors: ${{ steps.pr-checks.outputs.lint-errors }}, Warnings: ${{ steps.pr-checks.outputs.lint-warnings }}'
                  color: purple
                  github_token: ${{ secrets.GITHUB_TOKEN }}
